language: cpp
dist: bionic
os: linux

compiler:
  - gcc
  - clang

env:
  global:
    - CACHE_DIR=~/cached-deps
    - YCM_CHECKOUT=ycm-0.11
  matrix:
    - YARP_CHECKOUT=yarp-3.3
    - YARP_CHECKOUT=yarp-3.2

matrix:
  include:
    - if: type = cron
      compiler: gcc
      env: ROBOTOLOGY_CHECKOUT=master
    - if: type = cron
      compiler: clang
      env: ROBOTOLOGY_CHECKOUT=master

cache:
  directories: $CACHE_DIR

install:
  #-- Install YCM
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YCM
    --repo-url https://github.com/robotology/ycm
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YCM_CHECKOUT}"

  #-- Install YARP
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YARP
    --repo-url https://github.com/robotology/yarp
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YARP_CHECKOUT}"
    --additional-cmake-options "-DSKIP_ACE:BOOL=ON"
    --prepend-to-linker-path lib
    --additional-export-paths "YARP_DATA_DIRS;share/yarp"

before_script:
  - mkdir -p "$TRAVIS_BUILD_DIR/build" && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install"
  - make install

script:
  - echo "No unit tests available"

after_success:
  - make uninstall
